import os
import io
import csv
import json
import re
import datetime
import zipfile
import tarfile
import gzip
import bz2
import lzma
import shutil
import difflib
import hashlib
from xml.etree import ElementTree as ET
from pathlib import Path

from .utils import (
    FORMATS, IMAGE_EXTENSIONS, TEXT_EXTENSIONS, DATA_EXTENSIONS,
    ARCHIVE_EXTENSIONS, DOCUMENT_EXTENSIONS,
    detect_format, detect_format_by_ext, detect_format_by_magic,
    format_size, ensure_output_dir, get_output_path, compute_hash,
    is_text_file, detect_encoding, get_category
)

CATEGORY_TEMPLATES = {
    "txt": "# Welcome\n\nThis file was created by **Atulya Converter**.\n\n",
    "md": "# Welcome\n\nThis file was created by **Atulya Converter**.\n\n",
    "html": "<!DOCTYPE html><html><body><h1>Welcome</h1><p>Created by Atulya Converter.</p></body></html>",
    "csv": "name,email,age\nAlice,alice@example.com,30\nBob,bob@example.com,25",
    "tsv": "name\temail\tage\nAlice\talice@example.com\t30\nBob\tbob@example.com\t25",
    "json": '{\n  "name": "Example",\n  "version": "1.0",\n  "items": [1, 2, 3]\n}',
    "xml": '<?xml version="1.0" encoding="UTF-8"?>\n<root>\n  <item id="1">Value</item>\n</root>',
    "yaml": "name: Example\nversion: '1.0'\nitems:\n  - 1\n  - 2\n  - 3\n",
    "toml": 'title = "Example"\nversion = "1.0"\n\n[owner]\nname = "Alice"\n',
    "ini": "[settings]\nname=Example\nversion=1.0\n\n[database]\nhost=localhost\nport=5432\n",
    "py": '#!/usr/bin/env python3\n\ndef main():\n    print("Hello from Atulya!")\n\nif __name__ == "__main__":\n    main()\n',
    "js": '// Generated by Atulya Converter\nfunction greet(name) {\n  return `Hello, ${name}!`;\n}\n\nconsole.log(greet("World"));\n',
    "css": "/* Generated by Atulya Converter */\nbody {\n  font-family: sans-serif;\n  margin: 0;\n  padding: 20px;\n}\n",
    "env": "# Environment Configuration\nAPP_NAME=myapp\nAPP_ENV=development\nAPP_DEBUG=true\n",
    "sqlite": None,
    "log": "[2026-01-01 00:00:00] INFO  System started\n[2026-01-01 00:00:01] INFO  Ready\n",
    "cfg": "[server]\nhost = 0.0.0.0\nport = 8080\n\n[logging]\nlevel = info\n",
}

DOCX_TEMPLATE_B64 = None


def read_file(filepath, encoding="utf-8"):
    fmt = detect_format(filepath)
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"File not found: {filepath}")

    if fmt in IMAGE_EXTENSIONS or detect_format_by_ext(filepath) in ("jpg", "png", "webp", "bmp", "gif", "tiff", "ico"):
        return _read_image(filepath)
    elif detect_format_by_ext(filepath) in ("json",):
        return _read_json(filepath)
    elif detect_format_by_ext(filepath) in ("csv", "tsv"):
        return _read_table(filepath, fmt)
    elif detect_format_by_ext(filepath) in ("xlsx", "ods"):
        return _read_spreadsheet(filepath)
    elif detect_format_by_ext(filepath) in ("xml",):
        return _read_xml(filepath)
    elif detect_format_by_ext(filepath) in ("yaml", "yml"):
        return _read_yaml(filepath)
    elif detect_format_by_ext(filepath) in ("toml",):
        return _read_toml(filepath)
    elif detect_format_by_ext(filepath) in ("ini", "cfg", "conf"):
        return _read_ini(filepath)
    elif detect_format_by_ext(filepath) in ("zip", "tar", "gz", "bz2", "xz"):
        return _read_archive(filepath)
    elif detect_format_by_ext(filepath) in ("sqlite", "sqlite3", "db"):
        return _read_sqlite(filepath)
    elif detect_format_by_ext(filepath) in ("pdf",):
        return _read_pdf(filepath)
    elif detect_format_by_ext(filepath) in ("docx",):
        return _read_docx(filepath)
    elif detect_format_by_ext(filepath) in ("py", "js", "css"):
        with open(filepath, "r", encoding=encoding, errors="replace") as f:
            return {"format": fmt, "type": "code", "content": f.read(), "lines": f.name and None}
    else:
        with open(filepath, "r", encoding=encoding, errors="replace") as f:
            content = f.read()
        return {
            "format": fmt or "txt",
            "type": "text",
            "content": content,
            "lines": content.splitlines(),
            "encoding": encoding,
        }


def write_file(data, output_path, encoding="utf-8"):
    ensure_output_dir(output_path)
    fmt = detect_format_by_ext(output_path)
    ext = os.path.splitext(output_path.lower())[1]

    if fmt in ("json",):
        _write_json(data, output_path)
    elif fmt in ("csv", "tsv"):
        _write_table(data, output_path, fmt)
    elif fmt in ("xml",):
        _write_xml(data, output_path)
    elif fmt in ("yaml", "yml"):
        _write_yaml(data, output_path)
    elif fmt in ("toml",):
        _write_toml(data, output_path)
    elif fmt in ("ini", "cfg", "conf"):
        _write_ini(data, output_path)
    elif ext in IMAGE_EXTENSIONS:
        _write_image(data, output_path)
    elif fmt in ("zip",):
        _write_zip(data, output_path)
    else:
        if isinstance(data, str):
            content = data
        elif isinstance(data, dict) and "content" in data:
            content = data["content"]
        elif isinstance(data, dict) and "text" in data:
            content = data["text"]
        elif isinstance(data, list):
            content = json.dumps(data, indent=2)
        else:
            content = str(data)
        with open(output_path, "w", encoding=encoding) as f:
            f.write(content)


def convert_file(input_path, output_path, **kwargs):
    fmt_in = detect_format(input_path)
    fmt_out = detect_format_by_ext(output_path)
    if not fmt_out:
        fmt_out = os.path.splitext(output_path.lower())[1].lstrip(".")

    ensure_output_dir(output_path)

    _convert_by_format(input_path, output_path, fmt_in, fmt_out, kwargs)
    return format_size(os.path.getsize(output_path))


def create_file(output_path, template_name=None, **kwargs):
    ensure_output_dir(output_path)
    fmt = detect_format_by_ext(output_path) or os.path.splitext(output_path.lower())[1].lstrip(".")

    if template_name and template_name in CATEGORY_TEMPLATES:
        content = CATEGORY_TEMPLATES[template_name]
    elif fmt in CATEGORY_TEMPLATES:
        content = CATEGORY_TEMPLATES[fmt]
    elif fmt == "xlsx":
        _create_xlsx(output_path, kwargs)
        return format_size(os.path.getsize(output_path))
    elif fmt == "sqlite":
        _create_sqlite(output_path, kwargs)
        return format_size(os.path.getsize(output_path))
    else:
        content = f"Created by Atulya Converter\nFormat: {fmt}\nDate: {datetime.datetime.now()}\n"

    if isinstance(content, str):
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
    elif isinstance(content, bytes):
        with open(output_path, "wb") as f:
            f.write(content)

    return format_size(os.path.getsize(output_path))


def get_file_info(filepath):
    stat = os.stat(filepath)
    fmt = detect_format(filepath)
    cat = get_category(filepath)
    info = {
        "path": os.path.abspath(filepath),
        "name": os.path.basename(filepath),
        "size": stat.st_size,
        "size_human": format_size(stat.st_size),
        "format": fmt or "unknown",
        "category": cat,
        "modified": datetime.datetime.fromtimestamp(stat.st_mtime).isoformat(),
        "created": datetime.datetime.fromtimestamp(stat.st_ctime).isoformat(),
    }

    ext = os.path.splitext(filepath.lower())[1]
    if ext in IMAGE_EXTENSIONS:
        try:
            from PIL import Image
            img = Image.open(filepath)
            info["width"] = img.width
            info["height"] = img.height
            info["mode"] = img.mode
            info["dpi"] = img.info.get("dpi")
            try:
                info["format_detail"] = img.format_description
            except Exception:
                pass
        except ImportError:
            pass

    if cat == "text" or ext in TEXT_EXTENSIONS:
        try:
            with open(filepath, "r", encoding="utf-8", errors="replace") as f:
                content = f.read()
            lines = content.splitlines()
            info["lines"] = len(lines)
            info["chars"] = len(content)
            info["words"] = len(content.split())
            info["encoding"] = detect_encoding(filepath)
        except Exception:
            pass

    if ext == ".json":
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
            if isinstance(data, list):
                info["array_length"] = len(data)
            elif isinstance(data, dict):
                info["keys"] = list(data.keys())
        except Exception:
            pass

    if ext == ".pdf":
        try:
            import fitz
            doc = fitz.open(filepath)
            info["pages"] = len(doc)
            doc.close()
        except ImportError:
            try:
                info["pages"] = "unknown (install PyMuPDF)"
            except Exception:
                pass
        except Exception:
            pass

    return info


def compute_file_hash(filepath, algorithms=None):
    if algorithms is None:
        algorithms = ["md5", "sha1", "sha256"]
    result = {}
    for algo in algorithms:
        try:
            result[algo] = compute_hash(filepath, algo)
        except Exception as e:
            result[algo] = str(e)
    return result


def split_file(filepath, chunk_size_mb=10, output_dir=None):
    if output_dir is None:
        output_dir = os.path.dirname(filepath) or "."
    ensure_output_dir(output_dir)

    base = os.path.splitext(os.path.basename(filepath))[0]
    chunk_size = chunk_size_mb * 1024 * 1024
    parts = []

    with open(filepath, "rb") as f:
        part_num = 1
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            part_path = os.path.join(output_dir, f"{base}.part{part_num:03d}")
            with open(part_path, "wb") as pf:
                pf.write(chunk)
            parts.append(part_path)
            part_num += 1

    return parts


def merge_files(input_paths, output_path):
    ensure_output_dir(output_path)
    with open(output_path, "wb") as out:
        for path in input_paths:
            with open(path, "rb") as f:
                shutil.copyfileobj(f, out)
    return format_size(os.path.getsize(output_path))


def compress_archive(input_paths, output_path, archive_format="zip"):
    ensure_output_dir(output_path)

    if archive_format == "zip":
        with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for path in input_paths:
                zf.write(path, os.path.basename(path))
    elif archive_format == "tar":
        with tarfile.open(output_path, "w") as tf:
            for path in input_paths:
                tf.add(path, arcname=os.path.basename(path))
    elif archive_format == "targz":
        with tarfile.open(output_path, "w:gz") as tf:
            for path in input_paths:
                tf.add(path, arcname=os.path.basename(path))
    elif archive_format == "tarbz2":
        with tarfile.open(output_path, "w:bz2") as tf:
            for path in input_paths:
                tf.add(path, arcname=os.path.basename(path))
    elif archive_format == "tarxz":
        with tarfile.open(output_path, "w:xz") as tf:
            for path in input_paths:
                tf.add(path, arcname=os.path.basename(path))
    elif archive_format == "gz":
        if len(input_paths) == 1:
            with open(input_paths[0], "rb") as f_in:
                with gzip.open(output_path, "wb") as f_out:
                    shutil.copyfileobj(f_in, f_out)
        else:
            compress_archive(input_paths, output_path + ".tar", "tar")
            with open(output_path + ".tar", "rb") as f_in:
                with gzip.open(output_path, "wb") as f_out:
                    shutil.copyfileobj(f_in, f_out)
            os.remove(output_path + ".tar")
    else:
        raise ValueError(f"Unsupported archive format: {archive_format}")

    return format_size(os.path.getsize(output_path))


def extract_archive(input_path, output_dir):
    ensure_output_dir(output_dir)
    fmt = detect_format(input_path)

    if fmt == "zip":
        with zipfile.ZipFile(input_path, "r") as zf:
            zf.extractall(output_dir)
    elif fmt == "tar":
        with tarfile.open(input_path, "r") as tf:
            tf.extractall(output_dir)
    elif fmt == "gz":
        output_path = os.path.join(output_dir, os.path.splitext(os.path.basename(input_path))[0])
        with gzip.open(input_path, "rb") as f_in:
            with open(output_path, "wb") as f_out:
                shutil.copyfileobj(f_in, f_out)
    elif fmt == "bz2":
        output_path = os.path.join(output_dir, os.path.splitext(os.path.basename(input_path))[0])
        with bz2.open(input_path, "rb") as f_in:
            with open(output_path, "wb") as f_out:
                shutil.copyfileobj(f_in, f_out)
    elif fmt == "xz":
        output_path = os.path.join(output_dir, os.path.splitext(os.path.basename(input_path))[0])
        with lzma.open(input_path, "rb") as f_in:
            with open(output_path, "wb") as f_out:
                shutil.copyfileobj(f_in, f_out)
    else:
        raise ValueError(f"Unsupported archive format: {fmt}")

    extracted = os.listdir(output_dir)
    return extracted


def validate_file(filepath):
    fmt = detect_format(filepath)
    issues = []

    if not os.path.exists(filepath):
        return {"valid": False, "format": fmt, "issues": ["File not found"]}

    if fmt in ("json",):
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                json.load(f)
        except json.JSONDecodeError as e:
            issues.append(f"Invalid JSON: {e}")
    elif fmt in ("xml",):
        try:
            ET.parse(filepath)
        except ET.ParseError as e:
            issues.append(f"Invalid XML: {e}")
    elif fmt in ("yaml", "yml"):
        try:
            import yaml
            with open(filepath, "r", encoding="utf-8") as f:
                yaml.safe_load(f)
        except Exception as e:
            issues.append(f"Invalid YAML: {e}")
    elif fmt in ("toml",):
        try:
            import tomllib
            with open(filepath, "rb") as f:
                tomllib.load(f)
        except ImportError:
            import tomli
            with open(filepath, "rb") as f:
                tomli.load(f)
        except Exception as e:
            issues.append(f"Invalid TOML: {e}")
    elif fmt in ("csv", "tsv"):
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                reader = csv.reader(f)
                for i, row in enumerate(reader):
                    if i > 1000:
                        break
        except Exception as e:
            issues.append(f"CSV read error: {e}")
    elif fmt in ("zip",):
        try:
            with zipfile.ZipFile(filepath, "r") as zf:
                if zf.testzip():
                    issues.append(f"Corrupted zip: {zf.testzip()}")
        except Exception as e:
            issues.append(f"Invalid ZIP: {e}")
    elif fmt in IMAGE_EXTENSIONS or detect_format_by_ext(filepath) in IMAGE_EXTENSIONS:
        try:
            from PIL import Image
            img = Image.open(filepath)
            img.verify()
        except Exception as e:
            issues.append(f"Invalid image: {e}")
    elif fmt in ("pdf",):
        try:
            import fitz
            doc = fitz.open(filepath)
            doc.close()
        except ImportError:
            pass
        except Exception as e:
            issues.append(f"Invalid PDF: {e}")
    elif fmt in ("sqlite",):
        try:
            import sqlite3
            conn = sqlite3.connect(filepath)
            conn.cursor().execute("SELECT 1")
            conn.close()
        except Exception as e:
            issues.append(f"Invalid SQLite: {e}")
    elif fmt in ("docx",):
        try:
            import zipfile
            with zipfile.ZipFile(filepath, "r") as zf:
                if "word/document.xml" not in zf.namelist():
                    issues.append("Not a valid DOCX (missing word/document.xml)")
        except Exception as e:
            issues.append(f"Invalid DOCX: {e}")

    return {"valid": len(issues) == 0, "format": fmt, "issues": issues}


def search_file(filepath, pattern, encoding="utf-8"):
    results = []
    compiled = re.compile(pattern, re.IGNORECASE) if isinstance(pattern, str) else pattern

    if is_text_file(filepath):
        with open(filepath, "r", encoding=encoding, errors="replace") as f:
            for i, line in enumerate(f, 1):
                matches = list(compiled.finditer(line.rstrip()))
                if matches:
                    results.append({
                        "line": i,
                        "text": line.rstrip()[:200],
                        "matches": [m.group() for m in matches],
                        "positions": [m.start() for m in matches],
                    })
    else:
        try:
            from PIL import Image
            img = Image.open(filepath)
            import pytesseract
            text = pytesseract.image_to_string(img)
            for i, line in enumerate(text.splitlines(), 1):
                if compiled.search(line):
                    results.append({"line": i, "text": line[:200], "matches": [m.group() for m in compiled.finditer(line)]})
        except ImportError:
            pass

    return results


def count_stats(filepath):
    stats = {"size": format_size(os.path.getsize(filepath))}

    if is_text_file(filepath):
        with open(filepath, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
        lines = content.splitlines()
        stats["lines"] = len(lines)
        stats["chars"] = len(content)
        stats["chars_no_spaces"] = len(content.replace(" ", "").replace("\n", "").replace("\r", "").replace("\t", ""))
        stats["words"] = len(content.split())
        non_empty = [l for l in lines if l.strip()]
        stats["code_lines"] = len(non_empty)
        stats["empty_lines"] = len(lines) - len(non_empty)
        stats["max_line_length"] = max((len(l) for l in lines), default=0)
        stats["avg_line_length"] = round(sum(len(l) for l in lines) / max(len(lines), 1), 1)

    if os.path.splitext(filepath.lower())[1] in IMAGE_EXTENSIONS:
        try:
            from PIL import Image
            img = Image.open(filepath)
            stats["width"] = img.width
            stats["height"] = img.height
            stats["megapixels"] = round(img.width * img.height / 1_000_000, 2)
        except ImportError:
            pass

    return stats


def show_schema(filepath):
    fmt = detect_format(filepath)
    schema = {"format": fmt, "type": get_category(filepath)}

    if fmt in ("json",):
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)
        schema["root_type"] = type(data).__name__
        if isinstance(data, dict):
            schema["keys"] = list(data.keys())
            schema["key_count"] = len(data)
            _infer_types(data, schema)
        elif isinstance(data, list):
            schema["length"] = len(data)
            if data:
                schema["item_type"] = type(data[0]).__name__
                if isinstance(data[0], dict):
                    schema["item_keys"] = list(data[0].keys())
    elif fmt in ("csv", "tsv"):
        with open(filepath, "r", encoding="utf-8") as f:
            reader = csv.reader(f)
            headers = next(reader, [])
            schema["columns"] = headers
            schema["column_count"] = len(headers)
            rows = list(reader)
            schema["row_count"] = len(rows)
    elif fmt in ("xlsx",):
        try:
            import openpyxl
            wb = openpyxl.load_workbook(filepath, read_only=True)
            schema["sheets"] = wb.sheetnames
            schema["sheet_count"] = len(wb.sheetnames)
            ws = wb.active
            if ws:
                schema["active_sheet"] = ws.title
                schema["dimensions"] = ws.dimensions
            wb.close()
        except ImportError:
            schema["sheets"] = "unknown (install openpyxl)"
    elif fmt in ("xml",):
        tree = ET.parse(filepath)
        root = tree.getroot()
        schema["root_tag"] = root.tag
        schema["root_attribs"] = list(root.attrib.keys()) if root.attrib else None
        schema["children"] = list({child.tag for child in root})

    return schema


def generate_random(output_path, lines=10):
    ensure_output_dir(output_path)
    fmt = detect_format_by_ext(output_path) or os.path.splitext(output_path.lower())[1].lstrip(".")
    import random
    import string

    if fmt in ("json",):
        data = {f"field_{i}": f"value_{random.randint(1, 100)}" for i in range(lines)}
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
    elif fmt in ("csv", "tsv"):
        delimiter = "\t" if fmt == "tsv" else ","
        with open(output_path, "w", encoding="utf-8", newline="") as f:
            writer = csv.writer(f, delimiter=delimiter)
            writer.writerow(["id", "name", "value", "active"])
            for i in range(lines):
                writer.writerow([i, f"item_{i}", random.randint(1, 1000), random.choice([True, False])])
    elif fmt in ("xml",):
        root = ET.Element("records")
        for i in range(lines):
            item = ET.SubElement(root, "record", id=str(i))
            ET.SubElement(item, "name").text = f"item_{i}"
            ET.SubElement(item, "value").text = str(random.randint(1, 1000))
        tree = ET.ElementTree(root)
        tree.write(output_path, encoding="utf-8", xml_declaration=True)
    else:
        with open(output_path, "w", encoding="utf-8") as f:
            for i in range(lines):
                f.write(f"Line {i+1}: {''.join(random.choices(string.ascii_letters + string.digits, k=40))}\n")

    return format_size(os.path.getsize(output_path))


def diff_files(filepath_a, filepath_b):
    if is_text_file(filepath_a) and is_text_file(filepath_b):
        with open(filepath_a, "r", encoding="utf-8", errors="replace") as f:
            lines_a = f.readlines()
        with open(filepath_b, "r", encoding="utf-8", errors="replace") as f:
            lines_b = f.readlines()

        diff = list(difflib.context_diff(lines_a, lines_b, fromfile=filepath_a, tofile=filepath_b, n=3))
        return {"type": "text", "diff": diff, "diffs": len(diff) > 0}
    else:
        stat_a = os.stat(filepath_a)
        stat_b = os.stat(filepath_b)
        return {
            "type": "binary",
            "size_a": stat_a.st_size,
            "size_b": stat_b.st_size,
            "same_size": stat_a.st_size == stat_b.st_size,
            "hash_a": compute_hash(filepath_a, "sha256"),
            "hash_b": compute_hash(filepath_b, "sha256"),
            "identical": compute_hash(filepath_a, "sha256") == compute_hash(filepath_b, "sha256"),
        }


def batch_convert(input_dir, pattern, output_dir, output_format, **kwargs):
    import glob
    matched = glob.glob(os.path.join(input_dir, pattern))
    results = []
    for input_path in sorted(matched):
        base = os.path.splitext(os.path.basename(input_path))[0]
        output_path = os.path.join(output_dir, f"{base}.{output_format}")
        try:
            result = convert_file(input_path, output_path, **kwargs)
            results.append((base, "ok", result))
        except Exception as e:
            results.append((base, "error", str(e)))
    return results


# ------- Internal converters -------

def _convert_by_format(input_path, output_path, fmt_in, fmt_out, kwargs):
    ext_out = os.path.splitext(output_path.lower())[1]

    if fmt_in in ("csv", "tsv", "xlsx", "ods") and fmt_out in ("csv", "tsv", "xlsx", "json", "html", "xml"):
        _convert_tabular(input_path, output_path)
    elif fmt_in in ("json",) and fmt_out in ("csv", "xlsx", "xml", "yaml", "toml", "html"):
        _convert_json_to(input_path, output_path, fmt_out)
    elif fmt_in in ("yaml", "yml") and fmt_out in ("json", "csv", "xlsx", "xml"):
        _convert_yaml_to(input_path, output_path, fmt_out)
    elif fmt_in in ("xml",) and fmt_out in ("json", "csv", "xlsx", "yaml"):
        _convert_xml_to(input_path, output_path, fmt_out)
    elif fmt_in in ("html", "txt", "md", "log", "cfg", "env") and ext_out in {".txt", ".html", ".md"}:
        _convert_text_to(input_path, output_path, fmt_out)
    elif fmt_in in IMAGE_EXTENSIONS or ext_out in IMAGE_EXTENSIONS:
        _convert_image(input_path, output_path, kwargs.get("quality", 90))
    elif fmt_in == "pdf" and fmt_out in ("txt", "html", "json"):
        _convert_pdf(input_path, output_path, fmt_out)
    elif fmt_in in ("zip", "tar", "gz", "bz2", "xz") and fmt_out == "dir":
        extract_archive(input_path, output_path)
    else:
        data = read_file(input_path)
        write_file(data, output_path)


def _convert_tabular(input_path, output_path):
    import pandas as pd
    ext = os.path.splitext(input_path.lower())[1]
    if ext == ".csv":
        df = pd.read_csv(input_path)
    elif ext in (".tsv", ".tab"):
        df = pd.read_csv(input_path, sep="\t")
    else:
        df = pd.read_excel(input_path)
    out_ext = os.path.splitext(output_path.lower())[1]
    if out_ext == ".csv":
        df.to_csv(output_path, index=False)
    elif out_ext in (".xlsx", ".xls"):
        df.to_excel(output_path, index=False, engine="xlsxwriter")
    elif out_ext == ".json":
        df.to_json(output_path, orient="records", indent=2)
    elif out_ext == ".html":
        df.to_html(output_path, index=False)
    elif out_ext == ".xml":
        df.to_xml(output_path, index=False)


def _convert_json_to(input_path, output_path, target_fmt):
    import pandas as pd
    with open(input_path, encoding="utf-8") as f:
        data = json.load(f)
    if isinstance(data, list):
        df = pd.DataFrame(data)
    else:
        df = pd.DataFrame([data])
    if target_fmt == "csv":
        df.to_csv(output_path, index=False)
    elif target_fmt == "xlsx":
        df.to_excel(output_path, index=False, engine="xlsxwriter")
    elif target_fmt == "xml":
        df.to_xml(output_path, index=False)
    elif target_fmt == "yaml":
        import yaml
        with open(input_path) as f:
            d = json.load(f)
        with open(output_path, "w") as f:
            yaml.dump(d, f, default_flow_style=False)
    elif target_fmt == "toml":
        import tomli_w
        with open(input_path) as f:
            d = json.load(f)
        with open(output_path, "wb") as f:
            tomli_w.dump(d, f)


def _convert_yaml_to(input_path, output_path, target_fmt):
    import yaml
    import pandas as pd
    with open(input_path, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if target_fmt == "json":
        with open(output_path, "w") as f:
            json.dump(data, f, indent=2)
    else:
        if isinstance(data, list):
            df = pd.DataFrame(data)
        elif isinstance(data, dict):
            df = pd.DataFrame([data])
        else:
            df = pd.DataFrame()
        if target_fmt == "csv":
            df.to_csv(output_path, index=False)
        elif target_fmt == "xlsx":
            df.to_excel(output_path, index=False, engine="xlsxwriter")
        elif target_fmt == "xml":
            df.to_xml(output_path, index=False)


def _convert_xml_to(input_path, output_path, target_fmt):
    import pandas as pd
    tree = ET.parse(input_path)
    root = tree.getroot()
    records = []
    for child in root:
        record = {}
        for sub in child:
            record[sub.tag] = sub.text
        records.append(record)
    df = pd.DataFrame(records) if records else pd.DataFrame()
    if target_fmt == "json":
        df.to_json(output_path, orient="records", indent=2)
    elif target_fmt == "csv":
        df.to_csv(output_path, index=False)
    elif target_fmt == "xlsx":
        df.to_excel(output_path, index=False, engine="xlsxwriter")
    elif target_fmt == "yaml":
        import yaml
        with open(output_path, "w") as f:
            yaml.dump(records, f, default_flow_style=False)


def _convert_text_to(input_path, output_path, target_fmt):
    with open(input_path, encoding="utf-8", errors="replace") as f:
        content = f.read()
    if target_fmt == "txt":
        import html
        content = html.unescape(content)
        content = re.sub(r"<[^>]+>", "", content)
        content = content.replace("<br>", "\n").replace("</p>", "\n\n")
        content = "\n".join(l.strip() for l in content.splitlines() if l.strip())
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
    elif target_fmt == "html":
        content_lines = []
        for line in content.splitlines():
            content_lines.append(f"<p>{line}</p>" if line.strip() else "<br>")
        html_content = f"<!DOCTYPE html><html><body>{''.join(content_lines)}</body></html>"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html_content)


def _convert_image(input_path, output_path, quality):
    from PIL import Image
    img = Image.open(input_path)
    out_ext = os.path.splitext(output_path.lower())[1]
    if img.mode == "RGBA" and out_ext in (".jpg", ".jpeg"):
        img = img.convert("RGB")
    save_kwargs = {}
    if out_ext in (".jpg", ".jpeg"):
        save_kwargs["quality"] = quality
    elif out_ext == ".png":
        save_kwargs["compress_level"] = max(0, 9 - quality // 11)
    if out_ext == ".pdf":
        if img.mode != "RGB":
            img = img.convert("RGB")
        img.save(output_path, "PDF", resolution=100)
    else:
        img.save(output_path, **save_kwargs)


def _convert_pdf(input_path, output_path, target_fmt):
    text = _read_pdf_text(input_path)
    if target_fmt == "txt":
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(text)
    elif target_fmt == "html":
        html_content = f"<!DOCTYPE html><html><body><pre>{text}</pre></body></html>"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html_content)
    elif target_fmt == "json":
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump({"text": text}, f, indent=2)


def _read_pdf_text(filepath):
    try:
        import fitz
        doc = fitz.open(filepath)
        text = "\n".join(page.get_text() for page in doc)
        doc.close()
        return text
    except ImportError:
        try:
            import pdfplumber
            with pdfplumber.open(filepath) as pdf:
                return "\n".join(page.extract_text() or "" for page in pdf.pages)
        except ImportError:
            try:
                import pdfminer
            except ImportError:
                pass
    raise ImportError("PDF support requires PyMuPDF: pip install atulya-convert[pdf]")


# ------- Readers -------

def _read_image(filepath):
    from PIL import Image
    img = Image.open(filepath)
    return {
        "format": detect_format(filepath),
        "type": "image",
        "width": img.width,
        "height": img.height,
        "mode": img.mode,
        "path": filepath,
    }


def _read_json(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return {"format": "json", "type": "data", "data": data}


def _read_table(filepath, fmt):
    delimiter = "\t" if fmt == "tsv" else ","
    with open(filepath, "r", encoding="utf-8", newline="") as f:
        reader = csv.reader(f, delimiter=delimiter)
        rows = list(reader)
    return {
        "format": fmt,
        "type": "table",
        "headers": rows[0] if rows else [],
        "rows": rows[1:] if len(rows) > 1 else [],
        "row_count": max(0, len(rows) - 1),
        "column_count": len(rows[0]) if rows else 0,
    }


def _read_spreadsheet(filepath):
    import openpyxl
    wb = openpyxl.load_workbook(filepath, read_only=True, data_only=True)
    sheets = {}
    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        rows = []
        for row in ws.iter_rows(values_only=True):
            rows.append(list(row))
        sheets[sheet_name] = {"headers": rows[0] if rows else [], "rows": rows[1:] if len(rows) > 1 else []}
    wb.close()
    return {"format": "xlsx", "type": "workbook", "sheets": sheets, "sheet_names": wb.sheetnames}


def _read_xml(filepath):
    tree = ET.parse(filepath)
    root = tree.getroot()
    return {"format": "xml", "type": "data", "root_tag": root.tag, "data": _xml_to_dict(root)}


def _xml_to_dict(element):
    result = {}
    for child in element:
        if len(child) == 0:
            result[child.tag] = child.text
        else:
            if child.tag not in result:
                result[child.tag] = []
            result[child.tag].append(_xml_to_dict(child))
    return result


def _read_yaml(filepath):
    import yaml
    with open(filepath, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return {"format": "yaml", "type": "data", "data": data}


def _read_toml(filepath):
    try:
        import tomllib
        with open(filepath, "rb") as f:
            data = tomllib.load(f)
        return {"format": "toml", "type": "data", "data": data}
    except ImportError:
        import tomli
        with open(filepath, "rb") as f:
            data = tomli.load(f)
        return {"format": "toml", "type": "data", "data": data}


def _read_ini(filepath):
    import configparser
    config = configparser.ConfigParser()
    config.read(filepath, encoding="utf-8")
    data = {s: dict(config.items(s)) for s in config.sections()}
    return {"format": "ini", "type": "data", "data": data}


def _read_archive(filepath):
    fmt = detect_format(filepath)
    entries = []
    if fmt == "zip":
        with zipfile.ZipFile(filepath, "r") as zf:
            for info in zf.infolist():
                entries.append({"name": info.filename, "size": info.file_size, "compressed": info.compress_size})
    elif fmt == "tar":
        with tarfile.open(filepath, "r") as tf:
            for member in tf.getmembers():
                if member.isfile():
                    entries.append({"name": member.name, "size": member.size})
    return {"format": fmt, "type": "archive", "entries": entries, "count": len(entries)}


def _read_sqlite(filepath):
    import sqlite3
    conn = sqlite3.connect(filepath)
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
    tables = [row[0] for row in cursor.fetchall()]
    conn.close()
    return {"format": "sqlite", "type": "database", "tables": tables, "table_count": len(tables)}


def _read_pdf(filepath):
    text = _read_pdf_text(filepath)
    return {"format": "pdf", "type": "document", "content": text, "pages": text.count("\f") + 1 if text else 0}


def _read_docx(filepath):
    try:
        from docx import Document
        doc = Document(filepath)
        paragraphs = [p.text for p in doc.paragraphs]
        return {"format": "docx", "type": "document", "paragraphs": paragraphs, "count": len(paragraphs)}
    except ImportError:
        return {"format": "docx", "type": "document", "error": "Install python-docx: pip install atulya-convert[docx]"}


# ------- Writers -------

def _write_json(data, output_path):
    if isinstance(data, dict) and "data" in data:
        data = data["data"]
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, default=str)


def _write_table(data, output_path, fmt):
    delimiter = "\t" if fmt == "tsv" else ","
    if isinstance(data, dict):
        headers = data.get("headers", [])
        rows = data.get("rows", [])
    elif isinstance(data, list) and data and isinstance(data[0], dict):
        headers = list(data[0].keys())
        rows = [[row.get(h, "") for h in headers] for row in data]
    elif isinstance(data, list) and data and isinstance(data[0], list):
        headers = data[0] if data else []
        rows = data[1:] if len(data) > 1 else []
    else:
        headers = ["value"]
        rows = [[d] for d in data] if isinstance(data, list) else [[str(data)]]
    with open(output_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f, delimiter=delimiter)
        if headers:
            writer.writerow(headers)
        writer.writerows(rows)


def _write_xml(data, output_path):
    if isinstance(data, dict) and "data" in data:
        data = data["data"]
    if isinstance(data, dict):
        root = ET.Element("root")
        for key, val in data.items():
            child = ET.SubElement(root, key)
            child.text = str(val)
        tree = ET.ElementTree(root)
    elif isinstance(data, list):
        root = ET.Element("records")
        for i, item in enumerate(data):
            if isinstance(item, dict):
                record = ET.SubElement(root, "record", id=str(i))
                for k, v in item.items():
                    ET.SubElement(record, k).text = str(v)
        tree = ET.ElementTree(root)
    else:
        root = ET.Element("data")
        root.text = str(data)
        tree = ET.ElementTree(root)
    tree.write(output_path, encoding="utf-8", xml_declaration=True)


def _write_yaml(data, output_path):
    import yaml
    if isinstance(data, dict) and "data" in data:
        data = data["data"]
    with open(output_path, "w", encoding="utf-8") as f:
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True)


def _write_toml(data, output_path):
    try:
        import tomli_w
    except ImportError:
        raise ImportError("TOML writing requires tomli_w: pip install tomli-w")
    if isinstance(data, dict) and "data" in data:
        data = data["data"]
    with open(output_path, "wb") as f:
        tomli_w.dump(data, f)


def _write_ini(data, output_path):
    import configparser
    config = configparser.ConfigParser()
    if isinstance(data, dict) and "data" in data:
        data = data["data"]
    if isinstance(data, dict):
        for section, values in data.items():
            if isinstance(values, dict):
                config[section] = values
            else:
                config["DEFAULT"] = {section: str(values)}
    with open(output_path, "w", encoding="utf-8") as f:
        config.write(f)


def _write_image(data, output_path):
    from PIL import Image
    if isinstance(data, dict) and "path" in data:
        img = Image.open(data["path"])
    elif isinstance(data, str) and os.path.exists(data):
        img = Image.open(data)
    else:
        img = Image.new("RGB", (100, 100), "white")
    img.save(output_path)


def _write_zip(data, output_path):
    import io
    if isinstance(data, dict) and "entries" in data:
        with zipfile.ZipFile(output_path, "w") as zf:
            for entry in data["entries"]:
                if isinstance(entry, dict) and "name" in entry:
                    content = entry.get("content", b"") or b""
                    zf.writestr(entry["name"], content)


def _create_xlsx(output_path, kwargs):
    import openpyxl
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = kwargs.get("sheet", "Sheet1")
    headers = kwargs.get("headers", ["Column 1", "Column 2", "Column 3"])
    ws.append(headers)
    for i in range(kwargs.get("rows", 5)):
        ws.append([f"Value {i+1}_{j+1}" for j in range(len(headers))])
    wb.save(output_path)


def _create_sqlite(output_path, kwargs):
    import sqlite3
    conn = sqlite3.connect(output_path)
    cursor = conn.cursor()
    table_name = kwargs.get("table", "items")
    cursor.execute(f"CREATE TABLE IF NOT EXISTS {table_name} (id INTEGER PRIMARY KEY, name TEXT, value TEXT)")
    for i in range(kwargs.get("rows", 5)):
        cursor.execute(f"INSERT INTO {table_name} (name, value) VALUES (?, ?)", (f"item_{i}", f"value_{i}"))
    conn.commit()
    conn.close()


def _infer_types(data, schema):
    for key, val in data.items():
        schema[f"type_{key}"] = type(val).__name__
